// <auto-generated />
using System;
using Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace backend.Data.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260819185042_AddConceptoNombreUnidadCantidad")]
    partial class AddConceptoNombreUnidadCantidad
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.4")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("Data.Cliente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ApoderadoLegal")
                        .HasColumnType("text");

                    b.Property<string>("Ciudad")
                        .HasColumnType("text");

                    b.Property<string>("Contacto")
                        .HasColumnType("text");

                    b.Property<string>("DireccionFiscal")
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasColumnType("text");

                    b.Property<string>("Estatus")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("NombreComercial")
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .HasColumnType("text");

                    b.Property<string>("Rfc")
                        .HasColumnType("text");

                    b.Property<string>("Telefono")
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Clientes");
                });

            modelBuilder.Entity("Data.Concepto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clave")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("Precio")
                        .HasColumnType("double precision");

                    b.HasKey("Id");

                    b.ToTable("Conceptos");
                });

            modelBuilder.Entity("Data.HojaDeRuta", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("AsignadoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("FechaFinalizacion")
                        .HasColumnType("text");

                    b.Property<string>("FechaInicio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Folio")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Notas")
                        .HasColumnType("text");

                    b.Property<int>("PasoActual")
                        .HasColumnType("integer");

                    b.Property<string>("PresupuestoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProyectoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("HojasDeRuta");
                });

            modelBuilder.Entity("Data.Presupuesto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Clasificacion")
                        .HasColumnType("text");

                    b.Property<string>("ConceptosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("CostoDirectoConstruccion")
                        .HasColumnType("double precision");

                    b.Property<string>("Direccion")
                        .HasColumnType("text");

                    b.Property<string>("Estado")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("InfoAdicionalJson")
                        .HasColumnType("text");

                    b.Property<string>("Propietario")
                        .HasColumnType("text");

                    b.Property<string>("ProyectoId")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double?>("SupConstExistente")
                        .HasColumnType("double precision");

                    b.Property<double?>("SupIntervenir")
                        .HasColumnType("double precision");

                    b.Property<double?>("SupPredio")
                        .HasColumnType("double precision");

                    b.Property<string>("TipoVialidad")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<double>("TotalDirecto")
                        .HasColumnType("double precision");

                    b.Property<double>("TotalIndirecto")
                        .HasColumnType("double precision");

                    b.Property<string>("Uso")
                        .HasColumnType("text");

                    b.Property<string>("Version")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ZonaPrimaria")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Presupuestos");
                });

            modelBuilder.Entity("Data.Proyecto", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("Alcance")
                        .HasColumnType("text");

                    b.Property<string>("AreaCompatibilidad")
                        .HasColumnType("text");

                    b.Property<int>("Avance")
                        .HasColumnType("integer");

                    b.Property<int>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Descripcion")
                        .HasColumnType("text");

                    b.Property<string>("DireccionPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("DireccionesComplementariasJson")
                        .HasColumnType("text");

                    b.Property<string>("Estatus")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<DateTime>("FechaInicio")
                        .HasColumnType("timestamp without time zone");

                    b.Property<string>("ImpactoPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Responsable")
                        .HasColumnType("text");

                    b.Property<string>("UsoComplementario")
                        .HasColumnType("text");

                    b.Property<string>("UsoPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("UsosComplementariosJson")
                        .HasColumnType("text");

                    b.Property<string>("VialidadComplementaria")
                        .HasColumnType("text");

                    b.Property<string>("VialidadPrincipal")
                        .HasColumnType("text");

                    b.Property<string>("ZonaCompatibilidadEspecifica")
                        .HasColumnType("text");

                    b.Property<string>("ZonaPrimaria")
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Proyectos");
                });

            modelBuilder.Entity("Data.Rol", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Label")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Roles");
                });

            modelBuilder.Entity("Data.TareaDiaria", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("AsignadoA")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Etapa")
                        .HasColumnType("text");

                    b.Property<DateTime>("Fecha")
                        .HasColumnType("timestamp without time zone");

                    b.Property<bool>("Hecho")
                        .HasColumnType("boolean");

                    b.Property<int?>("PresupuestoId")
                        .HasColumnType("integer");

                    b.Property<string>("Prioridad")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ProyectoId")
                        .HasColumnType("text");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("TareasDiarias");
                });

            modelBuilder.Entity("Data.Usuario", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("text");

                    b.Property<string>("Avatar")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<int?>("ClienteId")
                        .HasColumnType("integer");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Contrasenia")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("ModulosJson")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasColumnType("text");

                    b.HasKey("Id");

                    b.ToTable("Usuarios");
                });
#pragma warning restore 612, 618
        }
    }
}
